# Generated by Django 5.0.6 on 2024-05-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_interno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobre',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
