# Generated by Django 5.0.6 on 2024-05-30 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_interno', '0002_alter_sobre_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('activate', models.BooleanField(default=True, verbose_name='Ativar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de publicação')),
            ],
            options={
                'verbose_name_plural': 'Categoria',
            },
        ),
        migrations.AlterField(
            model_name='operacional',
            name='activate',
            field=models.BooleanField(default=True, verbose_name='Ativar'),
        ),
        migrations.AlterField(
            model_name='operacional',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de publicação'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='activate',
            field=models.BooleanField(default=True, verbose_name='Ativar'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de publicação'),
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=300)),
                ('image_technical', models.ImageField(upload_to='imagens_tecnicos/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='site_interno.categoria')),
            ],
            options={
                'verbose_name_plural': 'Tecnico',
            },
        ),
    ]
