# Generated by Django 5.0.6 on 2024-05-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_interno', '0003_categoria_alter_operacional_activate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condominium_number', models.CharField(max_length=100)),
                ('condominium_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=250)),
                ('image_condominium', models.ImageField(upload_to='imagens_condominio/')),
                ('activate', models.BooleanField(default=True, verbose_name='Ativar')),
                ('creaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de publicação')),
            ],
            options={
                'verbose_name_plural': 'Condominio',
            },
        ),
    ]
