# Generated by Django 5.0.6 on 2024-05-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_interno', '0004_condominio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condominio',
            old_name='creaded_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='condominio',
            name='condominium_name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='condominium_number',
            field=models.CharField(max_length=100, verbose_name='Número do Condominio'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='description',
            field=models.TextField(max_length=250, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='image_condominium',
            field=models.ImageField(upload_to='imagens_condominio/', verbose_name='Inserir magem'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Titulo'),
        ),
    ]
