# Generated by Django 5.0.6 on 2024-06-03 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_interno', '0005_rename_creaded_at_condominio_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='operacional',
            name='descripiton',
            field=models.TextField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='operacional',
            name='image',
            field=models.ImageField(upload_to='imagens_operacionais/', verbose_name='Inserir Imagem'),
        ),
        migrations.AlterField(
            model_name='operacional',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='description',
            field=models.TextField(max_length=1000, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='image_company',
            field=models.ImageField(upload_to='imagens_sobre/', verbose_name='Inserir Imagem'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='site_interno.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='image_technical',
            field=models.ImageField(upload_to='imagens_tecnicos/', verbose_name='Inserir Imagem'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Titulo'),
        ),
    ]
