# Generated by Django 5.0.6 on 2024-06-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_interno', '0006_alter_categoria_title_alter_operacional_descripiton_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='activate',
            field=models.BooleanField(default=True, verbose_name='Ativar'),
        ),
    ]
