# Generated by Django 5.0.6 on 2024-06-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_interno', '0007_tecnico_activate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacional',
            old_name='descripiton',
            new_name='description',
        ),
    ]
