# Generated by Django 5.0.6 on 2024-06-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_interno', '0009_alter_operacional_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='image_technical',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_tecnicos/', verbose_name='Inserir Imagem'),
        ),
    ]
